version: '3.9'

services:
  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - static-data:/vol/web
    depends_on:
      - db

  db:
    image: postgres:15.4-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  proxy:
    build:
      context: ./configs/dev_proxy
    restart: always
    env_file:
      - .env
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-data:/vol/static


volumes:
  postgres-data:
  static-data:
