# Generated by Django 4.2 on 2023-04-27 12:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campain',
            fields=[
                ('title', models.CharField(blank=True, max_length=63, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(63)])),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ended', models.BooleanField(default=False)),
                ('game_masters', models.ManyToManyField(related_name='campains_gm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('owners', models.ManyToManyField(blank=True, related_name='tables_owned', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True, null=True)),
                ('campain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='campain_books.campain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=63, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('npc', 'Non-Player Character'), ('place', 'Place'), ('orga', 'Organisation'), ('event', 'Event'), ('notif', 'Notification'), ('note', 'Note')], max_length=31)),
                ('locked', models.BooleanField(default=True)),
                ('data_pc', models.TextField(blank=True, null=True)),
                ('data_gm', models.TextField(blank=True, null=True)),
                ('campain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campain_books.campain')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=63, unique=True)),
                ('tables', models.ManyToManyField(related_name='guests', to='campain_books.table')),
            ],
        ),
        migrations.CreateModel(
            name='CampainTemplate',
            fields=[
                ('title', models.CharField(blank=True, max_length=63, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(63)])),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.CharField(choices=[('misc', 'Miscellaneous'), ('DnD', 'Dungeons & Dragons'), ('LGM', 'Le Grand Monde'), ('SWd6', 'Star Wars d6'), ('SWd20', 'Star Wars d20'), ('NOC', 'NOC'), ('DH', 'Dark Heresy'), ('WH', 'Warhammer'), ('INS/MV', 'In Nomine Satanis/Magna Veritas'), ('Cthulhu', 'Call of Cthulhu'), ('Vampire', 'Vampire'), ('critical', 'Critical')], max_length=63)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('played_times', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='template', to='campain_books.campain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
