# Generated by Django 4.2 on 2023-05-25 13:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campain',
            fields=[
                ('title', models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(31)])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(31)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_ended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('official_site', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(blank=True, null=True)),
                ('table_password', models.CharField(blank=True, max_length=31, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('guests', models.ManyToManyField(blank=True, related_name='tables', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, related_name='tables_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(blank=True, max_length=31, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('campain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campain_pcs', to='campain_books.campain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=31, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=31, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('npc', 'Non-Player Character'), ('place', 'Place'), ('orga', 'Organisation'), ('event', 'Event'), ('note', 'Note'), ('recap', 'Recap')], max_length=31)),
                ('locked', models.BooleanField(default=True)),
                ('data_pc', models.TextField(blank=True, null=True)),
                ('data_gm', models.TextField(blank=True, null=True)),
                ('campain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campain_books.campain')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='CampainTemplate',
            fields=[
                ('title', models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(31)])),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(31)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('played_times', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campains', to='campain_books.game')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='template', to='campain_books.campain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campain',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_campains', to='campain_books.game'),
        ),
        migrations.AddField(
            model_name='campain',
            name='game_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campain_gm', to='campain_books.playercharacter'),
        ),
        migrations.AddField(
            model_name='campain',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_campains', to='campain_books.table'),
        ),
    ]
