# Generated by Django 4.2 on 2023-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_password',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
