# Generated by Django 4.2 on 2023-05-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0002_alter_playercharacter_campain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercharacter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campain_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
