# Generated by Django 4.2 on 2023-05-01 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0002_table_table_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='table',
            name='users',
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='guest',
            field=models.ManyToManyField(blank=True, related_name='tables', to='campain_books.guest'),
        ),
    ]
