# Generated by Django 4.2 on 2023-04-17 18:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0002_alter_item_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RemoveField(
            model_name='campain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='campaintemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='campain',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(63)]),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='game',
            field=models.CharField(choices=[('misc', 'Miscellaneous'), ('DnD', 'Dungeons & Dragons'), ('LGM', 'Le Grand Monde'), ('SWd6', 'Star Wars d6'), ('SWd20', 'Star Wars d20'), ('NOC', 'NOC'), ('DH', 'Dark Heresy'), ('WH', 'Warhammer'), ('INS/MV', 'In Nomine Satanis/Magna Veritas'), ('Cthulhu', 'Call of Cthulhu'), ('Vampire', 'Vampire'), ('critical', 'Critical')], max_length=63),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(63)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True, null=True)),
                ('campain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='campain_books.campain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
