# Generated by Django 4.2 on 2023-05-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0003_alter_playercharacter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
    ]
