# Generated by Django 4.2 on 2023-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0003_alter_item_options_remove_campain_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=63, unique=True)),
                ('tables', models.ManyToManyField(related_name='guests', to='campain_books.table')),
            ],
        ),
    ]
