# Generated by Django 4.2 on 2023-05-02 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0004_rename_guest_table_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
