# Generated by Django 4.2 on 2023-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0004_remove_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('NPC', 'Non-Player Character'), ('PLACE', 'Place'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap')], max_length=31),
        ),
    ]
