# Generated by Django 4.2 on 2023-05-11 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0005_alter_table_guests_delete_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campain',
            old_name='ended',
            new_name='is_ended',
        ),
        migrations.RemoveField(
            model_name='campain',
            name='game_masters',
        ),
        migrations.AddField(
            model_name='campain',
            name='game_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campain_gm', to=settings.AUTH_USER_MODEL),
        ),
    ]
