# Generated by Django 4.2 on 2023-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0005_item_image_url_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_unlocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap')], max_length=31),
        ),
    ]
