# Generated by Django 4.2 on 2023-05-11 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0006_rename_ended_campain_is_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='campains', to=settings.AUTH_USER_MODEL),
        ),
    ]
