# Generated by Django 4.2 on 2023-06-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0007_remove_item_author_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campain',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('cs', 'Czech'), ('zh', 'Chinese'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('no', 'Norwegian'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('vi', 'Vietnamese')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='campaintemplate',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaintemplate',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaintemplate',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('cs', 'Czech'), ('zh', 'Chinese'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('no', 'Norwegian'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('vi', 'Vietnamese')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='campain',
            name='game',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='game',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
