# Generated by Django 4.2 on 2023-05-12 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0007_campain_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playercharacter',
            name='campain',
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='campains',
            field=models.ManyToManyField(blank=True, related_name='campain_characters', to='campain_books.campain'),
        ),
        migrations.AlterField(
            model_name='campain',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='player_campains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='template', to='campain_books.campain'),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campain',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_campains', to='campain_books.game'),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campains', to='campain_books.game'),
        ),
    ]
