# Generated by Django 4.2 on 2023-06-02 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0008_campain_image_url_campain_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_password',
        ),
        migrations.AlterField(
            model_name='campain',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(63)]),
        ),
        migrations.AlterField(
            model_name='campain',
            name='game',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='campain',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(63)]),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(63)]),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='game',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(63)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='character_name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
