# Generated by Django 4.2 on 2023-05-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0008_game_remove_playercharacter_campain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='campain',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_campains', to='campain_books.table'),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='character_name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
