# Generated by Django 4.2 on 2023-05-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0009_alter_game_options_campain_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campain',
            name='players',
        ),
        migrations.AddField(
            model_name='campain',
            name='pcs',
            field=models.ManyToManyField(blank=True, related_name='pc_campains', to='campain_books.playercharacter'),
        ),
        migrations.AlterField(
            model_name='campain',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_campains', to='campain_books.table'),
        ),
    ]
