# Generated by Django 4.2 on 2023-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0009_delete_game_remove_table_table_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('cs', 'Czech'), ('zh', 'Chinese'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('no', 'Norwegian'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('vi', 'Vietnamese')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='campaintemplate',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('cs', 'Czech'), ('zh', 'Chinese'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('no', 'Norwegian'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('vi', 'Vietnamese')], default='en', max_length=2),
        ),
    ]
