# Generated by Django 4.2 on 2023-05-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0010_remove_campain_players_campain_pcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='game_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campain_gm', to='campain_books.playercharacter'),
        ),
    ]
