# Generated by Django 4.2 on 2023-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0011_remove_playercharacter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='data_gm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='data_pc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
