# Generated by Django 4.2 on 2023-06-05 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0012_playercharacter_data_gm_playercharacter_data_pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercharacter',
            old_name='data_public',
            new_name='data_player',
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campain_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
