# Generated by Django 4.2 on 2023-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0013_rename_data_public_playercharacter_data_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
