# Generated by Django 4.2 on 2023-06-05 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0015_alter_campain_game_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='game_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campain_gm', to=settings.AUTH_USER_MODEL),
        ),
    ]
