# Generated by Django 4.2 on 2023-06-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0016_alter_campain_game_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercharacter',
            old_name='character_name',
            new_name='name',
        ),
    ]
