# Generated by Django 4.2 on 2023-06-14 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0018_playercharacter_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('cs', 'Czech'), ('zh', 'Chinese'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('no', 'Norwegian'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('vi', 'Vietnamese')], default='en', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('times_played', models.IntegerField(default=0)),
                ('is_official', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=31, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], max_length=15)),
                ('locked', models.BooleanField(default=True)),
                ('date_unlocked', models.DateTimeField(blank=True, null=True)),
                ('data_pc', models.TextField(blank=True, null=True)),
                ('data_gm', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campain_books.collection')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('data_pc', models.TextField(blank=True, null=True)),
                ('data_player', models.TextField(blank=True, null=True)),
                ('data_gm', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='campain_books.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='playercharacter',
            options={'ordering': ('locked', '-user', '-name')},
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='campain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campain_pcs', to='campain_books.campain'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CampainTemplate',
        ),
    ]
