# Generated by Django 4.2 on 2023-06-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0019_collection_collectionitem_collectionpc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campain_books.collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectionpc',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='campain_books.collection'),
            preserve_default=False,
        ),
    ]
