# Generated by Django 4.2 on 2023-06-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0021_collection_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
