# Generated by Django 4.2 on 2023-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0023_alter_collection_options_collection_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-date_updated',)},
        ),
        migrations.AddField(
            model_name='collection',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
