# Generated by Django 4.2 on 2023-06-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0024_alter_collection_options_collection_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='type',
            field=models.CharField(blank=True, choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], max_length=15, null=True),
        ),
    ]
