# Generated by Django 4.2 on 2023-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0025_alter_collectionitem_type_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='type',
            field=models.CharField(choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], default='MEMO', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANISATION', 'Organisation'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], default='MEMO', max_length=15),
        ),
    ]
