# Generated by Django 4.2 on 2023-06-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0026_alter_collectionitem_type_alter_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ('type', '-date_created')},
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='date_unlocked',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='locked',
        ),
    ]
