# Generated by Django 4.2 on 2023-06-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0027_alter_collectionitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='official_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='type',
            field=models.CharField(choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANIZATION', 'Organization'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], default='MEMO', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('NPC', 'Non-Player Character'), ('LOCATION', 'Location'), ('ORGANIZATION', 'Organization'), ('EVENT', 'Event'), ('NOTE', 'Note'), ('RECAP', 'Recap'), ('MISC', 'Misc'), ('MEMO', 'Memo')], default='MEMO', max_length=15),
        ),
    ]
