# Generated by Django 4.2 on 2023-06-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0029_alter_collection_options_campain_is_collectionable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-is_official', 'rating', '-date_updated', 'game')},
        ),
    ]
