# Generated by Django 4.2 on 2023-06-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0030_alter_collection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='parent_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_campains', to='campain_books.collection'),
        ),
    ]
