# Generated by Django 4.2 on 2023-06-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0031_campain_parent_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campain',
            old_name='is_collectionable',
            new_name='is_collectible',
        ),
    ]
