# Generated by Django 4.2 on 2023-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0036_alter_playercharacter_campain'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='is_copy_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='game',
            field=models.CharField(default='', max_length=63),
        ),
    ]
