# Generated by Django 4.2 on 2023-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0038_alter_campain_game_alter_collection_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='title',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
