# Generated by Django 4.2 on 2023-08-07 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campain_books', '0041_remove_collection_times_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='game_masters',
            field=models.ManyToManyField(blank=True, related_name='tables_gm', to=settings.AUTH_USER_MODEL),
        ),
    ]
