# Generated by Django 4.2 on 2023-08-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0042_table_game_masters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='data_gm',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='data_pc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='name',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_gm',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_pc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=31),
        ),
    ]
