# Generated by Django 4.2 on 2023-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0030_alter_collection_options'),
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_collections',
            field=models.ManyToManyField(blank=True, related_name='fav_users', to='campain_books.collection'),
        ),
    ]
