# Generated by Django 4.1.7 on 2023-03-29 18:57

import _users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[_users.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[_users.validators.validate_username]),
        ),
    ]
