# Generated by Django 4.2 on 2023-05-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
