# Generated by Django 4.2 on 2023-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campain_books', '0043_alter_collectionitem_data_gm_and_more'),
        ('_users', '0002_user_fav_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_collections',
            field=models.ManyToManyField(related_name='fav_users', to='campain_books.collection'),
        ),
    ]
