# Generated by Django 4.2 on 2023-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
