# Generated by Django 4.2 on 2023-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homearticle_content_alter_homearticle_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearticle',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
