# Generated by Django 4.2 on 2023-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homearticle_content_alter_homearticle_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearticle',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
