# Generated by Django 4.2 on 2023-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homearticle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearticle',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homearticle',
            name='title',
            field=models.CharField(default='no title', max_length=255),
            preserve_default=False,
        ),
    ]
