# Generated by Django 4.2 on 2023-08-14 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homearticle_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homearticle',
            name='image_size',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
