# Generated by Django 4.2.5 on 2023-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_adminplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='active_stripe_portal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='active_stripe_subscriptions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='active_tip_me',
            field=models.BooleanField(default=False),
        ),
    ]
