# Generated by Django 4.2.4 on 2023-08-22 15:43

import app_cdn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cdn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=app_cdn.models.item_directory),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
