# Generated by Django 4.2.5 on 2023-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cdn', '0003_alter_project_options_alter_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'description', '-date']},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('js', 'JavaScript'), ('json', 'JSON'), ('css', 'CSS'), ('html', 'HTML'), ('img', 'Image'), ('doc', 'Document'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
